python ResolutionPlotCreator.py RVertex20Low
python ResolutionPlotCreator.py RVertex20High
python ResolutionPlotCreator.py ZVertex20Low
python ResolutionPlotCreator.py ZVertex20High
python ResolutionPlotCreator.py DCA20Low
python ResolutionPlotCreator.py DCA20High
python ResolutionPlotCreator.py NHits20Low
python ResolutionPlotCreator.py NHits20High
python ResolutionPlotCreator.py NHitsdEdx20High
python ResolutionPlotCreator.py NHitsFitOverNHitsPoss20Low
python ResolutionPlotCreator.py NHitsFitOverNHitsPoss20High
python ResolutionPlotCreator.py NSigmaPion20Low
python ResolutionPlotCreator.py NSigmaPion20High
python ResolutionPlotCreator.py NSigmaKaon20Low
python ResolutionPlotCreator.py NSigmaKaon20High
python ResolutionPlotCreator.py NSigmaProton20Low
python ResolutionPlotCreator.py NSigmaProton20High
python ResolutionPlotCreator.py MSquaredPion20Low
python ResolutionPlotCreator.py MSquaredPion20High
python ResolutionPlotCreator.py MSquaredKaon20Low
python ResolutionPlotCreator.py MSquaredKaon20High





python ResolutionPlotCreator.py RVertex30Low
python ResolutionPlotCreator.py RVertex30High
python ResolutionPlotCreator.py ZVertex30Low
python ResolutionPlotCreator.py ZVertex30High
python ResolutionPlotCreator.py DCA30Low
python ResolutionPlotCreator.py DCA30High
python ResolutionPlotCreator.py NHits30Low
python ResolutionPlotCreator.py NHits30High
python ResolutionPlotCreator.py NHitsdEdx30High
python ResolutionPlotCreator.py NHitsFitOverNHitsPoss30Low
python ResolutionPlotCreator.py NHitsFitOverNHitsPoss30High
python ResolutionPlotCreator.py NSigmaPion30Low
python ResolutionPlotCreator.py NSigmaPion30High
python ResolutionPlotCreator.py NSigmaKaon30Low
python ResolutionPlotCreator.py NSigmaKaon30High
python ResolutionPlotCreator.py NSigmaProton30Low
python ResolutionPlotCreator.py NSigmaProton30High
python ResolutionPlotCreator.py MSquaredPion30Low
python ResolutionPlotCreator.py MSquaredPion30High
python ResolutionPlotCreator.py MSquaredKaon30Low
python ResolutionPlotCreator.py MSquaredKaon30High





python ResolutionPlotCreator.py OuterEPDLow
python ResolutionPlotCreator.py OuterEPDHigh