star-submit XMLRunFile-RVertex20Low.xml
star-submit XMLRunFile-RVertex30Low.xml
star-submit XMLRunFile-RVertex20High.xml
star-submit XMLRunFile-RVertex30High.xml
star-submit XMLRunFile-ZVertex20Low.xml
star-submit XMLRunFile-ZVertex30Low.xml
star-submit XMLRunFile-ZVertex20High.xml
star-submit XMLRunFile-ZVertex30High.xml
star-submit XMLRunFile-DCA20Low.xml
star-submit XMLRunFile-DCA30Low.xml
star-submit XMLRunFile-DCA20High.xml
star-submit XMLRunFile-DCA30High.xml
star-submit XMLRunFile-NHits20Low.xml
star-submit XMLRunFile-NHits30Low.xml
star-submit XMLRunFile-NHits20High.xml
star-submit XMLRunFile-NHits30High.xml
star-submit XMLRunFile-NHitsdEdx20High.xml
star-submit XMLRunFile-NHitsdEdx30High.xml
star-submit XMLRunFile-NHitsFitOverNHitsPoss20Low.xml
star-submit XMLRunFile-NHitsFitOverNHitsPoss30Low.xml
star-submit XMLRunFile-NHitsFitOverNHitsPoss20High.xml
star-submit XMLRunFile-NHitsFitOverNHitsPoss30High.xml
star-submit XMLRunFile-NSigmaPion20Low.xml 
star-submit XMLRunFile-NSigmaPion30Low.xml
star-submit XMLRunFile-NSigmaPion20High.xml
star-submit XMLRunFile-NSigmaPion30High.xml
star-submit XMLRunFile-NSigmaKaon20Low.xml
star-submit XMLRunFile-NSigmaKaon30Low.xml
star-submit XMLRunFile-NSigmaKaon20High.xml
star-submit XMLRunFile-NSigmaKaon30High.xml
star-submit XMLRunFile-NSigmaProton20Low.xml
star-submit XMLRunFile-NSigmaProton30Low.xml
star-submit XMLRunFile-NSigmaProton20High.xml
star-submit XMLRunFile-NSigmaProton30High.xml
star-submit XMLRunFile-MSquaredPion20Low.xml
star-submit XMLRunFile-MSquaredPion30Low.xml
star-submit XMLRunFile-MSquaredPion20High.xml
star-submit XMLRunFile-MSquaredPion30High.xml
star-submit XMLRunFile-MSquaredKaon20Low.xml
star-submit XMLRunFile-MSquaredKaon30Low.xml
star-submit XMLRunFile-MSquaredKaon20High.xml
star-submit XMLRunFile-MSquaredKaon30High.xml
star-submit XMLRunFile-OuterEPDLow.xml
star-submit XMLRunFile-OuterEPDHigh.xml