star-submit XMLRunFile-RVertex20Low-V1,V2.xml
star-submit XMLRunFile-RVertex20High-V1,V2.xml
star-submit XMLRunFile-ZVertex20Low-V1,V2.xml
star-submit XMLRunFile-ZVertex20High-V1,V2.xml
star-submit XMLRunFile-DCA20Low-V1,V2.xml
star-submit XMLRunFile-DCA20High-V1,V2.xml
star-submit XMLRunFile-NHits20Low-V1,V2.xml
star-submit XMLRunFile-NHits20High-V1,V2.xml
star-submit XMLRunFile-NHitsdEdx20High-V1,V2.xml
star-submit XMLRunFile-NHitsFitOverNHitsPoss20Low-V1,V2.xml
star-submit XMLRunFile-NHitsFitOverNHitsPoss20High-V1,V2.xml
star-submit XMLRunFile-NSigmaPion20Low-V1,V2.xml 
star-submit XMLRunFile-NSigmaPion20High-V1,V2.xml
star-submit XMLRunFile-NSigmaKaon20Low-V1,V2.xml
star-submit XMLRunFile-NSigmaKaon20High-V1,V2.xml
star-submit XMLRunFile-NSigmaProton20Low-V1,V2.xml
star-submit XMLRunFile-NSigmaProton20High-V1,V2.xml
star-submit XMLRunFile-MSquaredPion20Low-V1,V2.xml
star-submit XMLRunFile-MSquaredPion20High-V1,V2.xml
star-submit XMLRunFile-MSquaredKaon20Low-V1,V2.xml
star-submit XMLRunFile-MSquaredKaon20High-V1,V2.xml