star-submit XMLRunFile-RVertex30Low-V1,V2.xml
star-submit XMLRunFile-RVertex30High-V1,V2.xml
star-submit XMLRunFile-ZVertex30Low-V1,V2.xml
star-submit XMLRunFile-ZVertex30High-V1,V2.xml
star-submit XMLRunFile-DCA30Low-V1,V2.xml
star-submit XMLRunFile-DCA30High-V1,V2.xml
star-submit XMLRunFile-NHits30Low-V1,V2.xml
star-submit XMLRunFile-NHits30High-V1,V2.xml
star-submit XMLRunFile-NHitsdEdx30High-V1,V2.xml
star-submit XMLRunFile-NHitsFitOverNHitsPoss30Low-V1,V2.xml
star-submit XMLRunFile-NHitsFitOverNHitsPoss30High-V1,V2.xml
star-submit XMLRunFile-NSigmaPion30Low-V1,V2.xml
star-submit XMLRunFile-NSigmaPion30High-V1,V2.xml
star-submit XMLRunFile-NSigmaKaon30Low-V1,V2.xml
star-submit XMLRunFile-NSigmaKaon30High-V1,V2.xml
star-submit XMLRunFile-NSigmaProton30Low-V1,V2.xml
star-submit XMLRunFile-NSigmaProton30High-V1,V2.xml
star-submit XMLRunFile-MSquaredPion30Low-V1,V2.xml
star-submit XMLRunFile-MSquaredPion30High-V1,V2.xml
star-submit XMLRunFile-MSquaredKaon30Low-V1,V2.xml
star-submit XMLRunFile-MSquaredKaon30High-V1,V2.xml
star-submit XMLRunFile-OuterEPDLow-V1,V2.xml
star-submit XMLRunFile-OuterEPDHigh-V1,V2.xml