#star-submit XMLRunFile-RVertex20Low-V3.xml
#star-submit XMLRunFile-RVertex20High-V3.xml
#star-submit XMLRunFile-ZVertex20Low-V3.xml
#star-submit XMLRunFile-ZVertex20High-V3.xml
#star-submit XMLRunFile-DCA20Low-V3.xml
#star-submit XMLRunFile-DCA20High-V3.xml
#star-submit XMLRunFile-NHits20Low-V3.xml
#star-submit XMLRunFile-NHits20High-V3.xml
#star-submit XMLRunFile-NHitsdEdx20High-V3.xml
#star-submit XMLRunFile-NHitsFitOverNHitsPoss20Low-V3.xml
#star-submit XMLRunFile-NHitsFitOverNHitsPoss20High-V3.xml
#star-submit XMLRunFile-NSigmaPion20Low-V3.xml 
#star-submit XMLRunFile-NSigmaPion20High-V3.xml
#star-submit XMLRunFile-NSigmaKaon20Low-V3.xml
#star-submit XMLRunFile-NSigmaKaon20High-V3.xml
#star-submit XMLRunFile-NSigmaProton20Low-V3.xml
star-submit XMLRunFile-NSigmaProton20High-V3.xml
#star-submit XMLRunFile-MSquaredPion20Low-V3.xml
#star-submit XMLRunFile-MSquaredPion20High-V3.xml
#star-submit XMLRunFile-MSquaredKaon20Low-V3.xml
#star-submit XMLRunFile-MSquaredKaon20High-V3.xml