/********************************************************************
* StEpdUtil_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error StEpdUtil_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableStEpdUtil_Dict();
extern void G__cpp_setup_inheritanceStEpdUtil_Dict();
extern void G__cpp_setup_typetableStEpdUtil_Dict();
extern void G__cpp_setup_memvarStEpdUtil_Dict();
extern void G__cpp_setup_globalStEpdUtil_Dict();
extern void G__cpp_setup_memfuncStEpdUtil_Dict();
extern void G__cpp_setup_funcStEpdUtil_Dict();
extern void G__set_cpp_environmentStEpdUtil_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "StBbcGeom.h"
#include "StEpdEpFinder.h"
#include "StEpdEpInfo.h"
#include "StEpdGeom.h"
#include "StEpdFastSim/StEpdFastSim.h"
#include "StEpdFastSim/StEpdTrivialEventGenerator.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__StEpdUtil_DictLN_TClass;
extern G__linked_taginfo G__StEpdUtil_DictLN_TBuffer;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMemberInspector;
extern G__linked_taginfo G__StEpdUtil_DictLN_TString;
extern G__linked_taginfo G__StEpdUtil_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TClonesArray;
extern G__linked_taginfo G__StEpdUtil_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TVector2;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__StEpdUtil_DictLN_TVector3;
extern G__linked_taginfo G__StEpdUtil_DictLN_StBbcGeom;
extern G__linked_taginfo G__StEpdUtil_DictLN_TFile;
extern G__linked_taginfo G__StEpdUtil_DictLN_TProfile;
extern G__linked_taginfo G__StEpdUtil_DictLN_TProfile2D;
extern G__linked_taginfo G__StEpdUtil_DictLN_StEpdGeom;
extern G__linked_taginfo G__StEpdUtil_DictLN_TH1D;
extern G__linked_taginfo G__StEpdUtil_DictLN_TH2D;
extern G__linked_taginfo G__StEpdUtil_DictLN_TH3D;
extern G__linked_taginfo G__StEpdUtil_DictLN_StEpdEpInfo;
extern G__linked_taginfo G__StEpdUtil_DictLN_StEpdEpFinder;
extern G__linked_taginfo G__StEpdUtil_DictLN_TRandom3;
extern G__linked_taginfo G__StEpdUtil_DictLN_StPicoEpdHit;
extern G__linked_taginfo G__StEpdUtil_DictLN_StEpdFastSim;
extern G__linked_taginfo G__StEpdUtil_DictLN_StEpdTrivialEventGenerator;

/* STUB derived class for protected member access */
